title:              Minseo Cho
email:              jms7180@cau.ac.kr
description: |
  Hi there!ðŸ‘‹<br>
  This page is where I share my projects, ideas, and learning journey.<br> 
  Feedback and inquiries are always welcome! ðŸ˜Š
author:             Minseo Cho
baseurl:            ""
url:                "https://MinseoCho03.github.io"

# Social Profiles
twitter_username:   
github_username:    MinseoCho03
facebook_username:  
instagram_username:  _iamminseo_03
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
